config/routes.rb
Rails.application.routes.draw do
  resources :links
  
  devise_for :users
  
  authenticated :user do
    root 'links#index', as: :authenticated_root
  end

  # Route to redirect short URLs to original URLs
  get '/:short_url', to: 'links#redirect', as: 'redirect'

  root to: redirect('/users/sign_in')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
    belongs_to :user

    validates :short_url, presence: true, uniqueness: true
    validates :long_url, presence: true


  private

  def generate_short_url
    self.short_url = SecureRandom.hex(4)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :links, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link, only: %i[show edit update destroy]
  before_action :load_user_links, only: [:index]

  def index
    @links = current_user.links
    @link = Link.new
  end

  def new
    @link = Link.new
  end

  def show
    redirect_to @link.long_url, allow_other_host: true
  end

  def create
    if current_user.nil?
      flash[:error] = "Please log in to create a link."
      redirect_to new_user_session_path
      return
    end
    
    @link = current_user.links.build(link_params)

    if link_params[:custom_url].present?
      @link.short_url = link_params[:custom_url]
    else
      @link.short_url = generate_short_url
    end

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @link.update(link_params)
      redirect_to links_path, notice: 'Link was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  def redirect
    @link = Link.find_by_short_url(params[:short_url])

    if @link
      @link.increment!(:clicks)
      if valid_url?(@link.long_url)
        redirect_to @link.long_url
      else
        redirect_to root_path, alert: 'Invalid URL for redirection'
      end
    else
      redirect_to root_path, alert: 'Short URL not found'
    end
  end

  private

  def set_link
    @link = current_user.links.find_by(id: params[:id])
    redirect_to root_path, alert: 'Link not found' unless @link
  end

  def load_user_links
    @links = current_user.links
  end

  def link_params
    params.require(:link).permit(:long_url, :custom_url, :short_url)
  end

  def generate_short_url
    loop do
      short_url = SecureRandom.hex(4)
      return short_url unless Link.exists?(short_url: short_url)
    end
  end

  def valid_url?(url)
    url.present? && (url.starts_with?('http://') || url.starts_with?('https://'))
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pwa_manifest_tags
    tag(:link, rel: 'manifest', href: '/manifest.json')
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-200 rounded-sm indent-1.5 w-full">
  <div class="container mx-auto">
    <div class="flex justify-between items-center py-4">
      <a href="/" class="text-4xl font-bold">Short</a>
      <button class="block lg:hidden px-2 text-gray-600 focus:outline-none" aria-label="Toggle navigation">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
        </svg>
      </button>
      <div class="hidden lg:block">
        <ul class="flex space-x-4">
          <li class="nav-item">
            <a href="#links" class="text-gray-600 hover:text-gray-900">Link</a>
          </li>
        </ul>
      </div>
      <div>
        <% if current_user %>
          <ul class="flex space-x-4">
            <li class="nav-item">
              <%= link_to "Edit Account", edit_user_registration_path, class: "text-gray-600 hover:text-gray-900" %>
            </li>
            <li class="nav-item">
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded" %>
            </li>
          </ul>
        <% else %>
          <ul class="flex space-x-4">
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "text-gray-600 hover:text-gray-900" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "text-gray-600 hover:text-gray-900 pr-4" %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shrt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="theme-color" content="#ffffff">
    <%= csrf_meta_tags %>
    <%= pwa_manifest_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-no-repeat bg-pack bg-cover bg-fixed bg-center bg-black bg-opacity-10 backdrop-blur-md">
    <main class="container mx-auto mt-28 px-5 flex flex-col">
    <%= render 'layouts/navbar' %>
      <%= yield %>
    </main>

    <script>
    document.addEventListener('DOMContentLoaded', function() {
      const links = document.querySelectorAll('a');
      links.forEach(link => {
        link.setAttribute('target', '_blank');
      });
    });
  </script>

    <script>
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('/service-worker.js')
        .then(registration => {
          console.log('Service Worker registered with scope:', registration.scope);
        })
        .catch(error => {
          console.error('Service Worker registration failed:', error);
        });
    });
  }
</script>

  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, class: "contents") do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <% if  @link.long_url.nil? %>
  <div class="my-5">
    <%= form.label :long_url %>
    <%= form.text_area :long_url, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <% end %>

  <div class="my-5">
    <%= form.label :custom_url %>
    <%= form.text_field :custom_url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Short url:</strong>
    <%= link.short_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Long url:</strong>
    <%= link.long_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Custom url:</strong>
    <%= link.custom_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Clicks:</strong>
    <%= link.clicks %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this link", link, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this link", edit_link_path(link), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/links/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing link</h1>

  <%= render "form", link: @link %>

  <%= link_to "Show this link", @link, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to links", links_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/links/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Links</h1>
    <%= link_to "New link", new_link_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="links" class="min-w-full">
    <%= render @links %>
  </div>
</div>

app/views/links/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New link</h1>

  <%= render "form", link: @link %>

  <%= link_to "Back to links", links_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/links/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @link %>

    <%= link_to "Edit this link", edit_link_path(@link), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this link", link_path(@link), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to links", links_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/main/home.html.erb
<div>
  <% if current_user %>
  Hello <%= current_user.email %>
  <% end %>
</div>